<style>
    header.page-header {
        box-shadow: 0px 0px 7px 0px rgb(0 0 0 / 20%);
        border-top: none;
        margin-bottom: 25px;
        z-index: 150;
        color: #000;
        background-color: #000;
    }

    .header.content {
        padding: 6px 0px 4px;
    }

    .logo {
        width: 30%;
        padding: 10px 0px 0px 10px;
        margin: 0px;
    }

    .logo img {
        width: 100%;
        height: auto;
        display: initial;
    }

    .block-search .nested {
        display: none;
    }

    /* header.page-header a,
        .alink {
            color: #f4f4f4;
        }

        header.page-header a:visited,
        .alink:visited {
            color: #f4f4f4;
        } */
    #clickme {
        color: #f4f4f4;
    }

    header.page-header a:hover,
    .alink:hover {
        color: #000;
        text-decoration: none;
    }

    .minicart-wrapper .action.showcart:hover:before {
        color: #ccc;
    }

    .block-search input {
        border-radius: 10px;
        height: 35px;
    }

    .userAcc {
        color: #f4f4f4;
        font-size: 35px;
        float: right;
        margin: 5px 15px 5px 5px;
    }

    button.btn.cancel {
        background-color: red;
        margin: 20px;
        padding: 15px 40px;
    }
    .navigation .level0.parent > .level-top{
        padding-right: 25px;
    }
    .navigation .level0.parent > .level-top > .ui-menu-icon:after{
        font-size: 35px;
    }
    .navigation .level0 .submenu li.parent > a > .ui-menu-icon:after{
        font-size: 35px;
    }
    /* div#usr_popup span a {
        color: #000;
        margin: 5px;
        padding: 10px 5px 5px 5px;
        display: block;
        border: 2px solid #000;
        border-style: none none outset inset;
        font-weight: bold;
    } */

    .navigation {
        font-weight: 550;
        font-size: 16px;
        background-color: #000;
    }

    .navigation .level0>.level-top {

        color: #f4f4f4;
        border: none !important;
    }

    .navigation .level0>.level-top:hover {
        color: #ccc;
    }

    .block-search {
        margin: 10px 5px 0px 5px;
    }

    .minicart-wrapper .action.showcart:before {
        font-size: 50px;
        color: #f4f4f4;
    }

    .minicart-wrapper {
        display: inline-block;
        position: relative;
        float: right;
        margin: 10px;
    }

    .block-search .label:before {
        font-size: 40px;
        color: #f4f4f4;
    }

    .block-search .label:hover:before {
        color: #ccc;
    }

    img.mobilelogo {
        display: none;
    }

    .nav-toggle:before {
        color: #f4f4f4;
        font-size: 35px;
    }

    a.mobile-logo {
        width: 20%;
        display: none;
    }

    .search-autocomplete {
        color: #000;
    }

    @media only screen and (max-width: 768px) {
        .header.content {
            padding-top: 10px;
        }

        .nav-toggle {
            position: absolute;
            top: 20px;
            right: 10px;
            left: auto;
        }

        .minicart-wrapper {
            margin: 20px 0px;
        }

        a.logo {
            padding: 10px 0px 10px 60px;
        }

        a.mobile-logo {
            width: 20%;
            display: inline-block;
        }

        a.logo {
            display: none;
        }

        img.mobilelogo {
            display: inline;
            width: 80px;
            height: auto;
            margin: 0px 10px;
        }

        .block-search {
            margin: 20px 0px 0px 0px;
            float: right;
            width: 45%;
        }

        .block-search .control {
            border: none;
        }
    }

    @media (min-width: 320px) and (max-width: 767px) {
        .sections.nav-sections {
            background: black;
        }
	.userAcc{
	 margin: 10px 50px 5px 5px;
	}
        .nav-toggle:hover:before {
            color: #f4f4f4;
        }

        .block-search {
            width: 30%;
        }
    }

    @media (min-width: 768px) {
        .nav-sections-item-content>.navigation {
            text-align: center;
            display: block;
        }

        .nav-sections {
            -webkit-flex-shrink: 0;
            flex-shrink: 0;
            -webkit-flex-basis: auto;
            flex-basis: auto;
            margin-bottom: 0 !important;
        }

        .navigation .level0.active>.level-top,
        .navigation .level0.has-active>.level-top {
            color: #f4f4f4
        }

        .block-search {
            float: left;
            padding-left: 30px;
            width: 35%;
        }
    }
</style>
