<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        header.page-header {
            box-shadow: 0px 0px 7px 0px rgb(0 0 0 / 20%);
            border-top: none;
            margin-bottom: 25px;
            z-index: 150;
            color: #000;
            background-color: #000;
        }

        .header.content {
            padding: 6px 0px 4px;
        }

        .logo {
            width: 30%;
            padding: 10px 0px 0px 10px;
            margin: 0px;
        }
        .logo img {
            width: 100%;
            height: auto;
            display: initial;
        }

        .block-search .nested {
            display: none;
        }

        /* header.page-header a,
        .alink {
            color: #f4f4f4;
        }

        header.page-header a:visited,
        .alink:visited {
            color: #f4f4f4;
        } */
        #clickme {
            color: #f4f4f4;
        }

        header.page-header a:hover,
        .alink:hover {
            color: #000;
            text-decoration: none;
        }

        .minicart-wrapper .action.showcart:hover:before {
            color: #ccc;
        }

        .block-search input {
            border-radius: 10px;
            height: 35px;
        }

        .userAcc {
            color: #f4f4f4;
            font-size: 35px;
            float: right;
            margin: 0px 10px 5px 5px;
        }

        #usr_popup {
            display: none;
            padding-top: 20px;
            text-align: left;
            position: fixed;
            top: 10%;
            width: 300px;
            right: 15px;
            border: 3px solid #f1f1f1;
            z-index: 20;
            background-color: #f4f4f4;
        }

        button.btn.cancel {
            background-color: red;
            margin: 20px;
            padding: 15px 40px;
        }

        div#usr_popup span a {
            color: #000;
            margin: 5px;
            padding: 10px 5px 5px 5px;
            display: block;
            border: 2px solid #000;
            border-style: none none outset inset;
            font-weight: bold;
        }

        .navigation {
            font-weight: 550;
            font-size: 16px;
            background-color: #000;
        }

        .navigation .level0>.level-top {

            color: #f4f4f4;
            border: none !important;
        }

        .navigation .level0>.level-top:hover {
            color: #ccc;
        }

        .block-search {
            margin: 10px 5px 0px 5px;
        }

        .minicart-wrapper .action.showcart:before {
            font-size: 50px;
            color: #f4f4f4;
        }

        .minicart-wrapper {
            display: inline-block;
            position: relative;
            float: right;
            margin: 10px;
        }

        .block-search .label:before {
            font-size: 40px;
            color: #f4f4f4;
        }

        .block-search .label:hover:before {
            color: #ccc;
        }

        img.mobilelogo {
            display: none;
        }

        .nav-toggle:before {
            color: #f4f4f4;
            font-size: 35px;
        }

        a.mobile-logo {
            width: 20%;
            display: none;
        }

        .search-autocomplete {
            color: #000;
        }

        @media only screen and (max-width: 768px) {
            .header.content {
                padding-top: 10px;
            }

            .userAcc {
                margin: 10px 60px 5px 5px;
            }

            .nav-toggle {
                position: absolute;
                top: 20px;
                right: 10px;
                left: auto;
            }

            .minicart-wrapper {
                margin: 20px 0px;
            }

            a.logo {
                padding: 10px 0px 10px 60px;
            }

            a.mobile-logo {
                width: 20%;
                display: inline-block;
            }

            #usr_popup {
                width: 250px;
            }

            a.logo {
                display: none;
            }

            img.mobilelogo {
                display: inline;
                width: 80px;
                height: auto;
                margin: 0px 10px;
            }

            .block-search {
                margin: 20px 0px 0px 0px;
                float: right;
                width: 45%;
            }

            .block-search .control {
                border: none;
            }
        }

        @media (min-width: 320px) and (max-width: 767px) {
            .sections.nav-sections {
                background: black;
            }

            .nav-toggle:hover:before {
                color: #f4f4f4;
            }

            .block-search {
                width: 30%;
            }
        }

        @media (min-width: 768px) {
            .nav-sections-item-content>.navigation {
                text-align: center;
                display: block;
            }

            .nav-sections {
                -webkit-flex-shrink: 0;
                flex-shrink: 0;
                -webkit-flex-basis: auto;
                flex-basis: auto;
                margin-bottom: 0 !important;
            }

            .navigation .level0.active>.level-top,
            .navigation .level0.has-active>.level-top {
                color: #f4f4f4
            }

            .block-search {
                float: left;
                padding-left: 30px;
                width: 35%;
            }
        }


        /* Process to checkout button */

        button#top-cart-btn-checkout {
            background: black;
        }
        
        button#top-cart-btn-checkout {
            background: black;
            border: 1px solid black;
        }

        button#top-cart-btn-checkout:hover {
            background: white;
            color: black;
            border: 1px solid black;
            transition: all 0.3s ease-in;
        }
    </style>
</head>

<body>
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $url = $storeManager->getStore()->getBaseUrl();
    ?>
    <a href="<?php echo $block->getBaseUrl(); ?>" class="mobile-logo"> <img src="<?php echo $block->getViewFileUrl('images/Vector-7.svg'); ?>" class="mobilelogo"></a>


    <div class="userAcc">
        <a href="#" id="clickme" onmouseover="openForm()"><i class="fa-solid fa-circle-user"></i></a>
    </div>

    <div id="usr_popup" onmouseover="openForm()" onmouseout="closeForm()">
        <span>
            <a href="<?= $url ?>customer/account/">My Account</a>
        </span>
        <span>
            <a href="<?= $url ?>wishlist/">My Wish List</a>
        </span>
        <span>
            <a href="<?= $url ?>customer/account/login/referer/"> Sign In </a>
        </span>
        <span>
            <a href="<?= $url ?>customer/account/create/">Create an Account</a>
        </span>
        <!-- <button type="button" class="btn cancel">Close</button> -->
    </div>

    <script>
        function openForm() {
            document.getElementById("usr_popup").style.display = "block";
        }

        function closeForm() {
            document.getElementById("usr_popup").style.display = "none";
        }
    </script>

</body>

</html>