<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div class="newsletter-img">
        <p><b>Subscribe to receive.</b>
            Monthly stories and insights</p>
        <img alt="newsletter" src="<?php echo $block->getViewFileUrl('images/newsletter-image.webp'); ?>">
    </div>

    <div class="custLink">
        <div class="footer_title">
            <h3>We are here<span>.</span></h3>
        </div>
        <div class="explore">
            <ul class="footerLinks">
                <li class="nav item">
                    <a href="#">Magento® 2 Extension</a>
                </li>
                <li class="nav item">
                    <a href="#">Wordpress</a>
                </li>
                <li class="nav item">
                    <a href="#">Shopify</a>
                </li>
                <li class="nav item">
                    <a href="#">Services</a>
                </li>
                <div class="socialLink">
                    <p>Get in Touch</p>
                </div>
                <li class="icons">
                    <a href="https://www.facebook.com/conceptivecommerce"><span><i class="fa-brands fa-square-facebook"></i></span></a>
                    <a href="https://www.instagram.com/conceptivecommerce/"><span><i class="fa-brands fa-square-instagram"></i></span></a>
                    <a href="https://www.linkedin.com/in/conceptive-commerce-0a6712178/"><span><i class="fa-brands fa-linkedin"></i></span></a>
                </li>
            </ul>
        </div>
        <div class="custadd">
            <ul class="address">
                <li> <img alt="indadd" src="<?php echo $block->getViewFileUrl('images/taj-mahal-5.png'); ?>"></li>
                <li class="nav item">
                    <p>509, Shreenath Signet Ii Ahmedabad, Gujarat, India : 380038</p>

                    <p>info@conceptivecommerce.com</p>

                    <p> +91 7600915332</p>
                </li>
                <li> <img alt="ausadd" src="<?php echo $block->getViewFileUrl('images/building-1.png'); ?>"></li>
                <li class="nav item">
                    <p> Manor Lakes, Victoria,Australia Post code : 3024</p>
                    <p> +61 434527631</p>
                </li>
            </ul>
        </div>
    </div>

    <div class="mapimg">
        <img alt="map" src="<?php echo $block->getViewFileUrl('images/mapimg.png'); ?>">
    </div>

</body>

</html>