<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        .userAcc {
            color: #f4f4f4;
            font-size: 35px;
            float: right;
            margin: 0px 10px 5px 5px;
        }
    </style>
</head>

<body>

    <div class="userAcc">
        <a href="#" id="clickme" onmouseover="openForm()"><i class="fa-solid fa-circle-user"></i></a>
    </div>
    <div class="custompop"  onmouseover="openForm()" onmouseout="closeForm()">

    </div>

    <script>
        function openForm() {
            document.getElementById("custompop").style.display = "block";
        }

        function closeForm() {
            document.getElementById("custompop").style.display = "none";
        }
    </script>

</body>

</html>