<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        .footer.content {
            box-sizing: content-box;
            background-color: #000;
            padding: 0px;
        }

        .block.newsletter {
            display: flex;
            width: 60%;
            padding: 95px 0px;
            background-color: #EBEFF0;
            max-width: 100%;
            align-content: center;
            justify-content: center;
            order: 0;
        }

        .footer .bugs {
            display: none;
        }

        .newsletter-img {
            width: 40%;
            float: left;
            background: #EBEFF0;
            justify-content: end;
            margin-bottom: 40px;
            align-items: end;
            display: flex;
        }

        .newsletter-img img {
            max-width: 100%;
            height: auto;
            border-bottom: 1px solid #EBEFF0;
        }

        .block.newsletter .field.newsletter {
            max-width: 100%;
        }

        .block.newsletter input {
            margin-right: 25px;
            padding: 30px 50px;
            font-size: 20px;
            border-radius: 30px;
        }

        .block.newsletter .field .control:before {
            font-size: 50px;
            line-height: 60px;
        }

        .action.primary,
        .action-primary {
            padding: 22px 30px;
            font-size: 18px;
        }
    </style>
</head>

<body>

</body>

</html>