<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        .footer.content {
            box-sizing: content-box;
            background-color: #000;
            padding: 0px;
            display: flex;
            flex-wrap: wrap;
        }

        .block.newsletter {
            display: flex;
            width: 45%;
            padding: 95px 0px;
            background-color: #EBEFF0;
            max-width: 100%;
            align-content: center;
            justify-content: center;
            order: 0;
        }

        .footer .bugs {
            display: none;
        }

        .newsletter-img {
            width: 55%;
            float: left;
            background: #EBEFF0;
            justify-content: end;
            margin-bottom: 40px;
            align-items: center;
            display: flex;
        }

        .newsletter-img img {
            max-width: 100%;
            height: auto;
            border-bottom: 1px solid #EBEFF0;
        }

        .block.newsletter .field.newsletter {
            max-width: 100%;
        }

        .block.newsletter input {
            margin-right: 15px;
            padding: 30px 50px;
            font-size: 20px;
            border-radius: 30px;
        }

        .block.newsletter .field .control:before {
            font-size: 50px;
            line-height: 60px;
        }

        .block.newsletter .action.subscribe {
            border-radius: 15px;
        }

        .action.primary,
        .action-primary {
            padding: 22px 30px;
            font-size: 18px;
        }

        .newsletter-img p {
            font-size: 30px;
            color: #3346af;
            text-align: center;
        }

        .footer_title {
            color: #F4F4F4;
        }

        .footer_title h3 {
            font-size: 40px;
            width: 100%;
            padding: 20px 0px;
            font-weight: bold;
        }

        .footer_title h3 span {
            color: #ff6700;
        }

        .socialLink {
            font-size: 20px;
            color: #F4F4F4;
        }

        .footer.content .links {
            display: none;
        }

        .footer.content .block {
            float: none;
        }

        .footer .copyright {
            display: block;
            order: 3;
            margin: 20px 0px;
            color: #f4f4f4;
            font-size: 20px;
            text-align: center;
            width: 100%;
        }

        .custLink {
            order: 3;
            width: 50%;
            font-size: 16px;
        }

        li.nav.item {
            margin-top: 15px;
            padding-bottom: 15px;
        }

        li.nav.item a {
            font-size: 20px;
        }

        .icons {
            font-size: 35px;
        }

        .custadd {
            order: 3;
            float: left;
            color: #F4F4F4;
            width: 40%;
        }

        .explore {
            padding: 30px;
            float: left;
            width: 40%;
        }

        .mapimg {
            order: 3;
            height: 50%;
            width: 50%;
            padding: 100px 0px;
        }

        .custadd .address {
            color: #F4F4F4;
            font-size: 14px;
        }

        @media only screen and (max-width: 768px){
            
        }

    </style>
</head>

<body>

</body>

</html>