<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        header.page-header {
            box-shadow: 0px 0px 7px 0px rgb(0 0 0 / 20%);
            border-top: none;
            margin-bottom: 25px;
            color: #fff;
            background-color: #000;
        }

        .header.content {
            height: 97px;
            padding: 6px 0px 4px;
            background-color: #000;
            color: #fff;
        }

        .nav-sections {
            height: 16.8px;
            padding-bottom: 17px;
            margin-bottom: 0px;
            background-color: #000;
        }

        ul.header.links {
            list-style: none;
            padding: 5px 0px;
            float: right;
            color: #fff;
        }

        .navigation {
            font-weight: 550;
            background-color: #000;
        }

        .navigation .level0>.level-top {
            line-height: 0px;
        }

        .sections.nav-sections {
            display: table;
        }

        i.fa-solid.fa-envelope {
            color: #fff;
            font-size: 20px;
            margin-right: 10px;
            display: inline;
        }
        .block-search .control{
            margin: 0px;
        }
        .navigation .level0 > .level-top{
            color: #fff;
        }
        .navigation .level0 > .level-top:hover{
            color: #ccc;
        }
        .minicart-wrapper .action.showcart:before{
            font-size: 50px;
            color: #fff;
        }
        .userAcc{
            color: #fff;
            font-size: 30px;
            margin-right: 10px;
        }
    </style>
</head>

<body>
   
</body>

</html>