<style>
    .catalog-category-view h1#page-title-heading {
        text-align: center;
        font-weight: 500;
    }


    /* For removing As Low As before price */
    .catalog-category-view .normal-price span.price-container.price-final_price.tax.weee span.price-label {
        display: none;
    }

    .catalog-category-view .product-item-inner {
        display: none;
    }

    /* .page-products .toolbar .limiter {
        display: block;
    } */

    /* .products.wrapper~.toolbar .limiter {
        display: none;
    } */
</style>