<div class="request-list">
    <div class="request-text">
        <p class="re_text">Have questions</p>
        <p class="re_txt">Let's talk!</p>
    </div>
    <div class="request-btn">
        <a href="http://localhost/magento244new/pub/contact" class="contact">Request</a>
    </div>
</div>
<div class="text_content">
    <div class="why_magento">
        <h2>Why Magento 2 Extensions?</h2>
        <p>To add custom features in your Magento store which isn't available in default Magento2 features, you need to integrate Magento add-ons. Installing Magento extensions provides Magento store with additional required features. SetuBridge Technolabs delivers best add-ons, modules, tools for all ecommerce aspects like:</p>
        <img alt="extension_use" src="<?php echo $block->getViewFileUrl('images/newTeam.png'); ?>">
        <ul>
            <li> <a href="">Customers' Data</a> </li>
            <li> <a href="">Catalog Management</a> </li>
            <li> <a href="">Marketing & Promotions</a> </li>
            <li> <a href="">Shipping</a> </li>
            <li> <a href="">Product Page Improvement</a> </li>
            <li> <a href="">Order Management</a> </li>
            <li> <a href="">SEO</a> </li>
            <li> <a href="">User Experience & Design</a> </li>
            <li> <a href="">Checkout</a> </li>
            <li> <a href="">B2B Products</a> </li>
            <li> <a href="">Support Channel & more...</a> </li>
        </ul>
    </div>
    <div class="why_trust">
        <h3>Why should you trust us?</h3>
        <p>We design plugins considering the problems of Magento merchants. All our plugins are designed to meet the requirements and solve the problems of the Magento store admins. We study the market, analyze all aspects of requirements apart from it being major or minor, implement, develop, and deliver the best performance extensions. Our Magento 2 modules are proven to assist the store management, conversion optimization, and sales-boosting of Magento 2 stores.</p>
        <p>
            This era is all about look and feel, ecommerce consumers are attracted by the sites providing a seamless and soothing shopping experience. SetuBridge’s M2 extensions enhance user experiences and increase conversion rates. Our extensions possess the qualities to attract visitors, turn them into customers and add them to the group of loyal customers.</p>
    </div>
    <div class="solution">
        <h3>SetuBridge Technolabs: Magento 2 One step solution</h3>
        <p>All of our Magento 2 extensions hold one basic quality and that’s easy and smooth set-up. To ensure a smooth installation, we provide free installation service to our customers. If the plugin is installed right and optimized correctly, it does wonders for online Magento stores by increasing conversion rates by 50%. </p>
        <p>Some of our extensions are specifically dedicated to well-known e-commerce industries, whether you need help setting up eye contact lens selling Magento store which allows customers to save and reuse the prescription or wants customs to get and design the product of their ideal thoughts. We have got solutions for all.</p>
        <p>For clear understanding and optimization of all Magento 2 modules, we provide back-end and front-end demos, user guidance, videos, description, screenshots, free installation, 6 months free support and 365 days of free updates. To connect better and understand requirements clearly, we also offer FREE LIVE DEMO for all M2 extensions. Magento store owners can schedule a live demo to understand the extension’s functionality in detail and share their custom requirements. For precise requirements, we also offer a customization service. Our developers integrate the present extension with the custom features and fulfil stated requirements.</p>
    </div>
</div>

<style>
    .request-list {
        background-color: #000;
        text-align: center;
        display: flex;
        padding: 20px 0px;
        width: 100%;
        flex-wrap: wrap;
        align-items: center;
        justify-content: center;
    }

    .request-text {
        display: flex;
        flex-wrap: wrap;
        font-size: 35px;
        color: #f4f4f4;
        width: 60%;
        justify-content: center;
        align-items: center;
        padding: 0;
    }

    .re_text:after {
        content: "?";
        vertical-align: middle;
        font-size: 101px;
        color: #f4a28b;
        font-weight: 700;
        padding: 0 0 11px;
    }

    .re_txt {
        padding-left: 20px;
    }

    .request-btn {
        width: 35%;
    }

    a.contact {
        width: 200px;
        background: #f4f4f4;
        border-radius: 30px;
        color: #000;
        font-size: 27px;
        padding: 10px 50px;
        border: 1px solid #777;
        box-shadow: -15px 0px 1px 5px #ccc, 15px 0px 1px 5px #ccc;
    }

    .text_content {
        text-align: left;
        padding: 10px 20px;
        line-height: 1.5;
        color: #000;
        font-size: 18px;
        font-weight: 500;
    }

    .why_magento {
        margin: 50px 0px;
    }

    .why_magento h2 {
        font-size: 38px;
        font-weight: 600;
        margin-bottom: 35px;
    }

    .why_magento p {
        letter-spacing: 1px;
    }

    .why_trust {
        margin: 50px 0px;
    }

    .why_trust h3 {
        font-size: 24px;
        font-weight: 700;
    }

    .why_trust p {
        padding: 10px 0px;
    }

    .solution {
        margin: 50px 0px;
    }

    .solution h3 {
        font-size: 24px;
        font-weight: 700;
    }

    .solution p {
        padding: 10px 0px;
    }

    @media screen and (max-width:768px) {

        .request-text {
            font-size: 25px;
        }

        .request-btn {
            width: 100%;
            padding: 25px 0px;
        }

        .re_txt {
            padding: 0px;
        }

        .re_text:after {
            font-size: 80px;
        }

        a.contact {
            font-size: 25px;
            padding: 10px 30px;
            box-shadow: -10px 0px 1px 2px #ccc, 10px 0px 1px 2px #ccc;
        }

        .text_content {
            font-size: 16px;
        }

        .why_magento h2 {
            font-size: 30px;
        }
    }

    @media screen and (min-width:320px) and (max-width:500px) {
        .re_text:after {
            font-size: 45px;
        }

        .text_content {
            font-size: 14px;
        }

        .request-text {
            font-size: 20px;
        }

        a.contact {
            font-size: 20px;
            padding: 8px 25px;

        }

        .solution h3 {
            font-size: 20px;
        }

        .request-list {
            padding-bottom: 10px;
        }

        .why_trust h3 {
            font-size: 20px;
        }

        .why_magento {
            margin: 25px 0px;
        }

        .why_trust {
            margin: 25px 0px;
        }

        .solution {

            margin: 25px 0px;

        }

        .why_magento h2 {
            font-size: 25px;
            margin-bottom: 20px;
        }
    }
</style>