<style>

    :root{
        --primary:#000;
        --secondary:white;
    }

    /* For the next btn on the product checkout shiping */
    /* For the login btn on the product checkout shiping */

    div#shipping-method-buttons-container .primary button,
    .actions-toolbar .primary button.action.login.primary,
    .actions-toolbar .primary button.action.primary.checkout,
    .actions-toolbar .primary button.action.action-apply,
    .actions-toolbar .primary a.action.primary.continue,
    .actions-toolbar .primary a.action.create.primary,
    .actions-toolbar .primary button.action.submit.primary,
    .actions-toolbar .primary button.action.save.primary,
    .actions-toolbar .primary button.action.primary.add,
    .catalogsearch-result-index .actions-primary button.action.tocart.primary,
    .actions-toolbar .primary button.action.tocart.primary,
    .actions-toolbar a.use-ajax.action.towishlist.action-towishlist,
    .item-actions .actions-toolbar a.action.action-edit,
    .item-actions .actions-toolbar a.action.action-delete,
    .cart.main.actions a.action.continue,
    .cart.main.actions button.action.update,
    .actions-primary button.action.tocart.primary,
    .actions-toolbar .primary button.action.apply.primary,
    ul.checkout.methods.items.checkout-methods-items .item button.action.primary.checkout,
    .actions-toolbar .primary button.action.primary.continue,
    .actions-toolbar .secondary button.action.update,
    .actions-toolbar .secondary button.action.add,
    .box-tocart.update .actions button#product-updatecart-button,
    .new-address-popup button.action.action-show-popup,
    .actions-toolbar .primary button.action.update,
    .actions-toolbar .primary button.action.share,
    .actions-toolbar .primary button.action.tocart,
    .block-content.content .block-actions button.action.select {
        background-color: var(--primary);
        color: var(--secondary);
        border: none;
        transition: all 0.5s ease-in;
    }

    div#shipping-method-buttons-container .primary button:hover,
    .actions-toolbar .primary button.action.login.primary:hover,
    .actions-toolbar .primary button.action.primary.checkout:hover,
    .actions-toolbar .primary button.action.action-apply:hover,
    .actions-toolbar .primary a.action.primary.continue:hover,
    .actions-toolbar .primary a.action.create.primary:hover,
    .actions-toolbar .primary button.action.submit.primary:hover,
    .actions-toolbar .primary button.action.save.primary:hover,
    .actions-toolbar .primary button.action.primary.add:hover,
    .catalogsearch-result-index .actions-primary button.action.tocart.primary:hover,
    .actions-toolbar .primary button.action.tocart.primary:hover,
    .actions-toolbar a.use-ajax.action.towishlist.action-towishlist:hover,
    .item-actions .actions-toolbar a.action.action-edit:hover,
    .item-actions .actions-toolbar a.action.action-delete:hover 
    .cart.main.actions a.action.continue:hover,
    .cart.main.actions button.action.update:hover,
    .actions-primary button.action.tocart.primary:hover,
    .actions-toolbar .primary button.action.apply.primary:hover,
    ul.checkout.methods.items.checkout-methods-items .item button.action.primary.checkout:hover,
    .actions-toolbar .primary button.action.primary.continue:hover
    .actions-toolbar .secondary button.action.update:hover,
    .actions-toolbar .secondary button.action.add:hover,
    .box-tocart.update .actions button#product-updatecart-button:hover,
    .new-address-popup button.action.action-show-popup:hover,
    .actions-toolbar .primary button.action.update:hover,
    .actions-toolbar .primary button.action.share:hover,
    .actions-toolbar .primary button.action.tocart:hover,
    .block-content.content .block-actions button.action.select:hover {
        background-color: var(--secondary);
        color: var(--primary);
        border: 1px solid var(--primary);
    }

</style>