<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>

  <style>
    .owl-carousel .owl-dots.disabled,
    .owl-carousel .owl-nav.disabled {
      display: block;
    }
    .fotorama-item{
      display: none;
    }
    h2.title {
        text-align: center;
    }
  </style>
</head>

<body>

  <?php
  $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
  $_product = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current product
  $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
  $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
  $images = $product->getMediaGallery();

  ?>
  <div class="main-title">
    <h2 class="title">ScreenShots Of Images</h2>
  </div>
  <div class="owl-carousel owl-theme">
    
    <?php

    if (count($images) > 0) { ?>
      <?php
      $i = 0;
      foreach ($images as $image) {
        foreach ($image as $child) {
          $i++;
          $productImage = $_imagehelper->init($product, 'product_page_image_large')
            ->setImageFile($child['file'])->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(285, 240)
            ->getUrl();

          $productImagedata = $_imagehelper->init($product, 'product_page_image_large')
            ->setImageFile($child['file'])->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(285, 240)
            ->getUrl();
          if ($i == 1) continue;

      ?>
          <div class="slide">
              <img data-id="smallthumbs-<?php echo $_product->getId(); ?>" data-img="<?php echo $productImagedata; ?>" src="<?php echo $productImage; ?>" />
          </div>
          <!-- <div class="item">
            <img src="<?php echo $productImage; ?>" alt="" />
          </div> -->

      <?php

        }
      }
      ?>

    <?php
    }
    ?>
  </div>
  <script>
    $(document).ready(function() {
      $('.owl-carousel').owlCarousel({
        loop: false,
        margin: 10,
        nav: true,
        responsive: {
          0: {
            items: 1
          },
          600: {
            items: 3
          },
          1000: {
            items: 3
          }
        }
      });
    })
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.js"></script>
</body>

</html>